env:
    credentials: "ENCRYPTED[5aae46bf2deddb150a353295a9950ed46d72d92ae4de42bfe7a8a09d70bf3a5eaa4d904faaa50a0fd2c4d857f0efc748]"
    rcloneconfig: "ENCRYPTED[321d965ddc9c4f951db8066d6cf99392857302e29fbb1e82ed1286614938aecc1eae36c71d1bf60127f6fddc006a3a7b]"
    tokentl: "ENCRYPTED[ac55b44fad8e3eaaeb2dfb3c3cf058f3c3dd838bca1faac712f5cd8ccbb46c78dbfe66d808991fd86f6095fc8e94e1f9]"
    idtl: "ENCRYPTED[acffabec2efd207dd1310a435adf7377021c8ef2c82c0fb932c5ff05e9af2d6faf88ed6fc58cb76f965ea0137e0e95a2]"
    lunch: lunch lineage_X00TD-user
    make: mka bacon

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 480m
  container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - echo "$rcloneconfig" > ~/.rclone.conf
       - git config --global user.name "aslenofarid"
       - git config --global user.email "yoniasleno.farid14@gmail.com"
       - echo "$credentials" > ~/.git-credentials
       - git config --global credential.helper store --file=~/.git-credentials
       - mkdir -p ~/ccache
       - rclone copy asleno:lineage/ccache.tar.gz ~/ -P
       - cd ~/
       - time tar xf ccache.tar.gz
       - cd ~/

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
      - ./w.sh

  Sync_script:
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="🔄 Start sync lineage-17.1 Source. . ."
      - mkdir -p ~/rom
      - cd ~/rom
      - sudo curl --create-dirs -L -o /usr/local/bin/repoo -O -L https://storage.googleapis.com/git-repo-downloads/repo
      - sudo chmod a+rx /usr/local/bin/repoo
      - repo init --depth=1 -u https://github.com/lineageos/android.git -b lineage-17.1 -g default,-mips,-darwin,-notdefault
      - git clone --depth=1 https://github.com/aslenofarid/local_manifest.git -b lineage-17.1 .repo/local_manifests
      - rm -rf .repo/repo && git clone https://gerrit.googlesource.com/git-repo .repo/repo
#      - sed -i 's|ssh://git@github.com|https://github.com|g' .repo/manifests/snippets/qassa.xml
#      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 --fail-fast
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
#      - sed -i 's| -u||g' vendor/qassa/config/branding.mk
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="✅ Sync Completed!"

  Build_script:
      - export BUILD_USERNAME="asleno"
#      - export WITH_GAPPS=true
      - sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="⏳ Build lineage-17.1 for X00TD Started. . ."
      - ./collect.sh
#      - ./final.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="✅ Build $(cd ~/rom/out/target/product/X00TD/ && ls lineage-*.zip) Completed!"

  Upload_script:
      - ./upload.sh
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="✅ Compress ccache"
      - ./ziping.sh
      - cd ~/
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="📤 Uploading ccache...."
      - rclone copy ccache.tar.gz asleno:lineage -P
      - curl -s https://api.telegram.org/$tokentl/sendMessage -d chat_id=$idtl -d text="✅ Ccache Uploaded Successfully!"
